Feature/addresourcename
launchbynttdata/tf-azurerm-module_reference-application_gateway pull request #2
Opened 2024-12-12 11:35 UTC by nidhi-sahu-nttd

defining a separate block 'resource_names_v2' so the update in the version of the reference module 'resource name' can be utilized using the new variable without breaking the existing module

2024-12-12 14:13 UTC, erick-floresca-nttd requested changes
looks good to me.
I think the comments in variables.tf are useful but needs guidance on style.

2024-12-19 18:50 UTC, erick-floresca-nttd approved these changes

2024-12-19 19:26 UTC, kevin11-allen-nttd requested changes
this won't change the resource names. we've added the `resource_names_v2` module, but we aren't using it anywhere.

wherever we are using the current `resource_names` module, we must now conditionally use the `resource_names_v2` module instead, based on the new variable.

for example, on the `name` input of the `resource_group`, we need a conditional
![image](https://github.com/user-attachments/assets/09c4840a-6200-4b8b-9675-ec2c211e58e8)

2024-12-20 15:14 UTC, kevin11-allen-nttd commented on locals.tf
> +  public_ip             = local.use_v2_resource_names ? module.resource_names_v2["public_ip"].standard : module.resource_names["public_ip"].standard
this is a minor thing, but could we rename this to `public_ip_name`?

2024-12-20 17:23 UTC, kevin11-allen-nttd approved these changes

2025-01-02 16:13 UTC, erick-floresca-nttd approved these changes

2025-01-03 15:39 UTC, merged